### ISSUE TITLE
Freezing/Stuttering from texture streaming

### ISSUE THREAD

**Issue by AdamGalt** [virtual-programming/specops-linux#1]
During game play there is a very noticeable constant stuttering/freezing that occurs every few seconds (presumably as textures are loading in?). If you do not progress forwards, the problem does not occur.

There is not a heavy load on CPU or SSD during these periods of stuttering.

**System**
```
 Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3613 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.0.2-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 560/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 349.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1201
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.91" x 11.77"  (23.98" diag)
                                            53.1cm x 29.9cm  (60.9cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2048 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: USB Mixer
    
Memory:
    RAM:  7987 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Blue
    Total Hard Disk Space Available:  104485 Mb
    Largest Free Hard Disk Block:  27303 Mb
```

If I can provide anything further to help narrow down the exact cause please let me know.

**Comment by vpltd-peterm** [comment]
Experiment with editing the PoolSize amount, under [TextureSettings] in the config file SREngine.ini

Due to the non-multithreaded nature of OpenGL, background loading as used by the Unreal engine is not as optimal as it is on Windows.

**Comment by AdamGalt** [comment]
Thank you.

I have now doubled the PoolSize and MemoryMargin values over standard and am seeing a very significant decrease in stuttering events, during brief testing. (yay!)

I will continue to experiment to find optimal values for my set up and report back with findings.

**Comment by AdamGalt** [comment]
I have obtained my best results by setting PoolSize: 450 and MemoryMargin: 30.

For anyone else reading this, config files are found at:

/home/**[USER]**/.local/share/yager/specops/GameDocuments/My Games/SpecOps-TheLine/SRGame/Config/

There are still a rare hiccups, usually when transitioning to a new area, but the frequency is massively reduced and overall is very playable now. I understand this is not something that can be fixed completely, due to limitations with OGL, so am closing this issue.

Thank you for your help.

**Comment by licaon-kter** [comment]
[TextureStreaming] ? I have no [TextureSettings] section.

**Comment by AdamGalt** [comment]
Yes the section is called "**TextureStreaming**" in the file "**SREngine.ini**" found at:

home/**[USER]**/.local/share/yager/specops/GameDocuments/My Games/SpecOps-TheLine/SRGame/Config/

**Comment by licaon-kter** [comment]
BTW mine is at **~/.local/yager/specops/GameDocuments/My Games/SpecOps-TheLine/SRGame/Config/** not in */share/*

**Comment by AdamGalt** [comment]
Placement in /share/ may be Arch specific oddity, or vice versa. Good to know though.

Are the changes working for you?

**Comment by vpltd-peterm** [comment]
We respect the XDG standard, the default for storage is ~/.local/share but if your distro sets XDG_DATA_HOME, that will be used instead.

**Comment by licaon-kter** [comment]
Yeah, I apparently had that set up, don't remember why now though.

**Comment by piedar** [comment]
The game is at least playable with

    PoolSize=450
    MemoryMargin=30

but there's still really bad stutter (down to 0.25 fps) when loading textures.  It happens most often when dropping off a ledge or zipline into a new area.  The stuttering coincides with disk activity.

Is there a way to tell the game to start loading textures before it needs them?
