### ISSUE TITLE
No Sound in Early Screens

### ISSUE THREAD

**Issue by ekianjo** [virtual-programming/specops-linux#13]
Not a big issue because it's not vital, but all the screens that load up before reaching the game menu do not have any sound at all. I believe they would have some kind of background effect, but they are missing at least on my machine (OpenSUSE 13,1, nVidia gtx460, i5 - while I dont believe this is anything specs related).

**Comment by vpltd-peterm** [comment]
If you are referring to the opening movies, e.g. the Unreal Technology logo, they are silent.

**Comment by ekianjo** [comment]
Oh, you mean they are silent even in the Windows version ?

**Comment by vpltd-peterm** [comment]
yes. it confused us at first, too :) The first time you hear sound is when the menu appears and you get Jimi Hendrix's star-spangled banner

**Comment by ekianjo** [comment]
OH! This is the first game where I do not hear any sound in such intro movies... glad to know it's not a Linux specific issue or something! Will close this.
