### ISSUE TITLE
No sound without pulseaudio

### ISSUE THREAD

**Issue by Betaversiondot** [virtual-programming/specops-linux#17]
Debian 9 x64 (Testing), ALSA 1.1.0. No sound/music in game. Installing pshhaudio solves this, but brings problems in other games/software. Please, add support for ALSA.

**Comment by vpltd-peterm** [comment]
SpecOps uses openal-soft for its audio. We have a custom build of it, libopenal-eon.so.1 in the game folder, however this is just because we wanted a more recent version than the steam-runtime contained.

You may want to try installing libopenal-soft i386, removing our build, and symlinking to your system version. Note that it needs to be openal-soft 1.16.0 or better to work.

**Comment by Betaversiondot** [comment]
Symlinking to /usr/lib/i386-linux-gnu/libopenal.so.1.16.0 didn't help.

**Comment by licaon-kter** [comment]
@Betaversiondot Can you follow my post and install pulse like that: https://forums.inxile-entertainment.com/viewtopic.php?f=34&t=13974&start=20#p161374

Although, this should work w/o Pulse, no idea about DOS (I already had the combo above made for WL2)

**Comment by vpltd-peterm** [comment]
It looks as if all these games are using openal-soft... so the problem is really openal-soft on Debian, not the game itself.

**Comment by Betaversiondot** [comment]
@licaon-kter Ah well, if that still requires installing pulseaudio, i'd better install it before playing Spec Ops and uninstall it after, rather than having it in my system all the time (even if it's not used). It just a matter of 1-2 minets, so not a big problem. Still, i hope in your next games Pulseaudio will not be a requirement, as it's not a requirement in more than 150 games in my library. Thank you for your time.

@vpltd-peterm Well, except for videos in D:OS, of all my games Spec Ops is the only game, that have problems with sound if pulseoudio is not installed. Anyway, thanks for help.

Closing.

**Comment by vpltd-peterm** [comment]
Judging by the output of D:OS there is a problem with opening the ALSA default audio device on Debian.

You can specifically force openal to use ALSA by creating an .alsoftrc file. See http://repo.or.cz/w/openal-soft.git/blob/HEAD:/alsoftrc.sample for the format of this file.

Short version: ALSA support should work. If it is not with openal-soft, there is a system issue.

**Comment by licaon-kter** [comment]
Like I said SO:TL does not need it, that setup should respond to apps requesting Pulse but not make it default for the whole system.


/PS: FYI, AFAICS:
* after setting up like this Mplayer based video players need a -400ms delay to make audio resync in ALSA mode, while Pulse mode just freezes the video; not sure if that's at fault but I did not invest the time to rip Pulse out again;
* Pulse comes default in Debian for some time now, but not being able to set it up for multiple sources (aka music player blocks browser sound) made me just uninstall it right away.

**Comment by Betaversiondot** [comment]
Creating .asoundrc with 
`pcm.!default {
    type hw
    card 0
}

ctl.!default {
    type hw
    card 0
}`

did the job.

**Comment by Betaversiondot** [comment]
Updating to latest Steam Beta (Feb 23rd) also fixes this bug.
`Updated ALSA libraries in the Steam Runtime to prevent compatibility issues with newer distributions`

**Comment by licaon-kter** [comment]
10x for the info
