### ISSUE TITLE
Dark shadows are red, bright light sources/reflections are light blue

### ISSUE THREAD

**Issue by sakuramboo** [virtual-programming/specops-linux#6]
http://images.akamai.steamusercontent.com/ugc/47630581270948379/FEB9CD4815D69CDDEEAC1964463FCCE48509F417/

It is hard to get the light blue colors but I will try to get a picture of it. But, I think both issues are related.

**Comment by vpltd-peterm** [comment]
System specs please? Also where are you seeing this?

**Comment by sakuramboo** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3c
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  4001 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
Network Information:
    Network Speed:  
    
Operating System Version:
    Ubuntu 14.04.2 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-53-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780/PCIe/SSE2

    Driver Version:  4.5.0 NVIDIA 349.16
    OpenGL Version: 4.5
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x1004
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                            50.9cm x 28.6cm  (58.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
    
Sound card:
    Audio device: Realtek ALC892
    
Memory:
    RAM:  15990 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  381329 Mb
    
Installed software:
    
Recent Failure Reports:
    Fri May 22 21:01:43 2015 GMT: file ''/tmp/dumps/crash_20150522170110_5.dmp'', upload yes: ''CrashID=bp-c82e2b19-3fbb-4b6b-933b-73d002150522''
    


Light blue colors scene from light sources
http://i.imgur.com/JGsDtXL.jpg
http://i.imgur.com/0OYhqoX.jpg
http://i.imgur.com/Ic9m1cn.jpg
http://i.imgur.com/ymv1vkj.jpg

Red seen on black textures
http://i.imgur.com/59ma8ht.jpg
http://i.imgur.com/i1zaRgu.jpg
http://i.imgur.com/pJoFzyp.jpg

Black blocks found on the chapter select screen
http://i.imgur.com/DY5hHkY.jpg

**Comment by vpltd-peterm** [comment]
Please check that you do not have "texture sharpening" enabled in the Nvidia control panel - we've seen this option cause such effects

**Comment by sakuramboo** [comment]
Well, I'll be. That was it. So, it's a problem with nVidia's drivers.

Very good.
