### ISSUE TITLE
The game's menu will sometimes be at 5 FPS

### ISSUE THREAD

**Issue by sakuramboo** [virtual-programming/specops-linux#7]
When I was trying to troubleshoot the last bug I submitted, I would start the game and when it would load the main menu, the game would be at 5 FPS and it would be locked there. I would quit and reload the game a few times until it would finally be at 60 FPS. It doesn't happen all the time and when it does I just keep restarting the game until it plays how it should.

**Comment by robertc** [comment]
We're already discussing that in #5 .

**Comment by sakuramboo** [comment]
Dupe.
