### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by lminiero** [virtual-programming/specops-linux#8]
I'm getting no sound at all when starting Spec Ops: The Line on my x86_64 Fedora 21. Since the engine is supposedly the same (not sure about that), I guess this might be related to https://github.com/virtual-programming/bioshockinfinite-linux/issues/17 but the instructions there (using the OS 32bit libopenal instead of the provided one) didn't work for me.

System Information:
https://gist.github.com/lminiero/6a6726b3f2e816798531

eon.txt content:
https://gist.github.com/lminiero/aad1c50382a928cc6522

Anythin else I can provide to check what's wrong?

**Comment by licaon-kter** [comment]
What sound system? ALSA? Pulse?

**Comment by vpltd-peterm** [comment]
Try using OpenAL-soft's logging :
https://github.com/kcat/openal-soft/blob/master/env-vars.txt

**Comment by lminiero** [comment]
I'm using Pulse, which is the detault in Fedora 21. I'll try and get some logs out of openal-soft.

**Comment by lminiero** [comment]
You can find a log generated with ```ALSOFT_LOGLEVEL=3``` here:
https://gist.github.com/lminiero/f9a7ccc19abf2f7e54f1

**Comment by vpltd-peterm** [comment]
This seems to suggest quadrophonic sound is being used. Is it possible that your system is configured for this, and audio is being sent to the wrong output ? Try overriding the default format with .alsoftrc

**Comment by lminiero** [comment]
Just tried that:

     [general]
     channels = stereo
     drivers =

and it still didn't work. An empty ```drivers``` means try them all, I also tried with just ```pulse``` and ```alsa``` and it had no effect.

Putting the game in windowed mode I could verify in ```pavucontrol``` (the Pulse mixer application) that a ```specsops.i386``` process appears in the playout tab, and that it's neither muted nor with its levels set to 0: it's just not playing anything, apparently.

**Comment by lminiero** [comment]
Is there any openal-soft test application I can try, just to check if it really is an issue with the openal-soft setup on my machine? I'm not really familiar with it. If you have some source code that collects this kind of debug to a file, I can compile and launch it in order to gather whatever info you might require.

**Comment by vpltd-peterm** [comment]
There are examples in the openal-soft sourcecode, which you can find at http://kcat.strangesoft.net/openal.html

**Comment by lminiero** [comment]
I tried a couple of those (alloopback, alreverb) and they worked as expected.

**Comment by vpltd-peterm** [comment]
Did you compile them as 32-bit versions ?

**Comment by Betaversiondot** [comment]
No sound in Spec Ops: The Line on Debian 9 x64. ALSA, no pulseaudio, Realtek integrated card.

**Comment by licaon-kter** [comment]
`steam steam://rungameid/50300` yields any errors?

**Comment by Betaversiondot** [comment]
In terminal?
```
beta@beta-version-pc:~$ steam steam://rungameid/50300
Running Steam on debian  64-bit
STEAM_RUNTIME is enabled automatically
[2016-02-13 22:27:50] Startup - updater built Feb  4 2016 12:22:08
[2016-02-13 22:27:50] Проверка установки...
[2016-02-13 22:27:50] Verification complete
Running Steam on debian  64-bit
STEAM_RUNTIME has been set by the user to: /home/beta/.steam/ubuntu12_32/steam-runtime
```

**Comment by lminiero** [comment]
Sorry, forgot to mention that after upgrading my OS (more recent version of Fedora) audio started working and I managed to play the whole game without any problem. Closing the issue as it's not there for me anymre.
